# Generated by Django 4.0.2 on 2022-02-19 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evernote', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visits',
            new_name='VisitCount',
        ),
    ]
