# Generated by Django 4.0.2 on 2022-02-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evernote', '0002_rename_visits_visitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcount',
            name='no_of_visits',
            field=models.IntegerField(default=0),
        ),
    ]
