# Generated by Django 4.0.2 on 2022-02-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evernote', '0005_countpage_delete_blog_delete_visitcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countpage',
            name='content',
            field=models.IntegerField(),
        ),
    ]
